config/routes.rb
Rails.application.routes.draw do
  resources :papers

  root 'home#index'

  resources :authors

  

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord

    has_and_belongs_to_many :papers
    validates :last_name, presence: true, length: { minimum: 1 }

    def name
        "#{first_name} #{last_name}"
    end

end

app/models/paper.rb
class Paper < ApplicationRecord
    has_and_belongs_to_many :authors
    validates :title, presence: true, length: { minimum: 1 }
    validates :venue, presence: true, length: { minimum: 1 }
    validates :year, presence: true, numericality: { only_integer: true }

    def self.published_in_year(year)
        where("year = ?", year)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  
  def index
    @authors = Author.all
  end

  def new
  end

  def show
    @author = Author.find(author_id_params)
  end

  def create
    @author = Author.new(new_author_params)

    @author.save
    redirect_to root_path, notice: 'Success!'
  end

  private
  def new_author_params
    params.require(:author).permit(:first_name, :last_name, :homepage)
  end

  private
  def author_id_params
    params.require(:id)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  
  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find(author_id_params)
  end

  def destroy
    @author = Author.find(author_id_params)
    @author.destroy
   
    redirect_to authors_path
  end

  def show
    @author = Author.find(author_id_params)
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to authors_path, notice: 'Success!'
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(author_id_params)

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  private
  def author_params
    params.require(:author).permit(:first_name, :last_name, :homepage)
  end

  private
  def author_id_params
    params.require(:id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: %i[ show edit update destroy ]

  # GET /papers
  def index
    year = params[:year]
    @papers = year.nil? ? Paper.all : Paper.published_in_year(year)
  end

  # GET /papers/1
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  def create
    @paper = Paper.new(paper_params)

    if @paper.save
      redirect_to @paper, notice: "Paper was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /papers/1
  def update
    if @paper.update(paper_params)
      redirect_to @paper, notice: "Paper was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /papers/1
  def destroy
    @paper.destroy
    redirect_to papers_url, notice: "Paper was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paper_params
      params.require(:paper).permit(:title, :venue, :year, author_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/authors/edit.html.erb
<h1>Edit Author</h1>
<%= form_for :author, url: author_path(@author), method: :patch do |form| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited
        this author from being saved:
      </h2>
      <ul>
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name %>
  </p>

  <p>
    <%= form.label :homepage %><br>
    <%= form.text_area :homepage %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
  <p>
    <%= link_to 'Back', authors_path %>
  </p>
<% end %>

app/views/authors/index.html.erb
<h1>Listing Authors</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Homepage</th>
  </tr>
 
  <% @authors.each do |author| %>
    <tr>
      <td><%= link_to author.name, author_path(author) %></td>
      <td><%= link_to author.homepage, "http://#{author.homepage}" %></td>
      <td><%= link_to "Edit", edit_author_path(author) %></td>
      <td><%= link_to "Delete", author_path(author), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>

<br />
<%= link_to "New", new_author_path %>

app/views/authors/new.html.erb
<%= form_with url: "/authors", scope: :author, local: true do |form| %>

  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited
        this author from being saved:
      </h2>
      <ul>
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name %>
  </p>

  <p>
    <%= form.label :homepage %><br>
    <%= form.text_area :homepage %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
  <p>
    <a href="/authors">Back</a>
  </p>
<% end %>

app/views/authors/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>Homepage:</strong>
  <%= @author.homepage %>
</p>

<p>
  <%= link_to 'Edit', edit_author_path(@author) %>
</p>

<p>
  <%= link_to 'Back', authors_path %>
</p>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paper Management System</h1>
You are seeing the rendered view of 'views/home/index.html.erb'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Intro Exercise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/papers/_form.html.erb
<%= form_with(model: paper) do |form| %>
  <% if paper.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
        <% paper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :venue, style: "display: block" %>
    <%= form.text_field :venue %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label "Authors", style: "display: block" %>
    <%= form.select 'author_ids',
      options_from_collection_for_select(Author.all, :id, :name, paper.author_ids),
      {},
    multiple: true, size: 10 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/papers/_paper.html.erb
<div id="<%= dom_id paper %>">
  <p>
    <strong>Title:</strong>
    <%= paper.title %>
  </p>

  <p>
    <strong>Venue:</strong>
    <%= paper.venue %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= paper.year %>
  </p>
  <p>
    <strong>Authors:</strong>
    <% paper.authors.each do |author| %>
      <p><%= author.name %></p>
    <% end %>
  </p>

</div>

app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render "form", paper: @paper %>

<br>

<div>
  <%= link_to "Show this paper", @paper %> |
  <%= link_to "Back to papers", papers_path %>
</div>

app/views/papers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Papers</h1>

<div id="papers">
  <% @papers.each do |paper| %>
    <%= render paper %>
    <p>
      <%= link_to "Show this paper", paper %>
      <%= link_to "Edit this paper", edit_paper_path(paper) %>
      <td><%= link_to "Delete", paper_path(paper), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
    </p>
  <% end %>
</div>

<%= link_to "New paper", new_paper_path %>

app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render "form", paper: @paper %>

<br>

<div>
  <%= link_to "Back to papers", papers_path %>
</div>

app/views/papers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @paper %>

<div>
  <%= link_to "Edit this paper", edit_paper_path(@paper) %> |
  <%= link_to "Back to papers", papers_path %>

  <%= button_to "Destroy this paper", @paper, method: :delete %>
</div>